import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import MessagesCtrl from '../component/messages.ctrl'
import { UserInputProvider, useUserInput } from '../store/user.input'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>My Auto Ai Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Description />
        <Center />
      </main>
    </>
  )
}

function GridBlock() {
  return <div className={styles.grid}>

  </div>
}
const MessagesWindow = () => (
  <div style={{ maxWidth: 320, display: 'flex', flexDirection: 'column', flex: 1 }}>
    <Messages />
    <Input />
  </div>
)
const Messages = () => (
  <div style={{ display: 'flex', flex: 9, border: '2px solid grey', }}>
    <MessagesCtrl />
  </div>
)
const Input = () => {
  const { onSubmit } = useUserInput();

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const input = (event.target as any).elements.myInput as HTMLInputElement;
    onSubmit(input.value);
  }

  return (
    <div style={{ display: 'flex', flex: 1, border: '2px solid grey', }}>
      <form onSubmit={handleSubmit} style={{ width: '100%', display: 'flex', }}>
        <input name="myInput" type="text" style={{ display: 'flex', flex: 8 }} />
        <button style={{ display: 'flex', flex: 2 }} type="submit">提交</button>
      </form>
    </div>
  )
}
function Center() {
  return (
    <div className={styles.center}>
      <LeftRight>
        <Left />
        <Right />
      </LeftRight>
    </div>
  )
}

const LeftRight = ({ children }: { children: JSX.Element[] }) => (
  <div style={{ display: 'flex', flex: 1 }}>{children}</div>
)
const Left = () => (
  <div style={{ display: 'flex', flex: 1, border: '2px solid grey', width: 300, height: 300 }}>
    <GridBlock />
  </div>
)
const Right = () => (
  <div style={{ display: 'flex', flex: 1, border: '2px solid grey', width: 300, height: 300 }}>
    <UserInputProvider>
      <MessagesWindow />
    </UserInputProvider>
  </div>
)


function Description() {
  return <div className={styles.description}>
    <p>
      Top Bar any infos&nbsp;
    </p>
    <div>
    </div>
  </div>
}

